# Generated by Django 5.2.7 on 2025-10-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0002_auto_20251004_2035'),
    ]

    operations = [
        # Make KYC keys nullable
        migrations.AlterField(
            model_name='kycrisk',
            name='natural_person_key',
            field=models.CharField(
                max_length=255, blank=True, null=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kycrisk',
            name='legal_person_key',
            field=models.CharField(
                max_length=255, blank=True, null=True, db_index=True),
        ),
        # Make ConsignmentAgreement borrower nullable temporarily
        migrations.AlterField(
            model_name='consignmentagreement',
            name='borrower',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='agreements', to='core_db.borrower'),
        ),
    ]
