# Generated by Django 5.2.7 on 2025-10-05 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0003_auto_20251004_2044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvestmentOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount', max_digits=18)),
                ('monthly_rate', models.DecimalField(decimal_places=6, help_text='Monthly interest rate', max_digits=9)),
                ('annual_rate', models.DecimalField(decimal_places=6, help_text='Annual CET rate', max_digits=9)),
                ('term_months', models.IntegerField(help_text='Loan term in months')),
                ('risk_level', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('proposta', 'Proposta'), ('encerrada', 'Encerrada')], default='aberta', max_length=15)),
                ('valid_until', models.DateTimeField(help_text='Offer validity date')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_offers', to='core_db.borrower')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
