# Generated by Django 5.2.7 on 2025-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0004_borrower_user_investor_user_investmentoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='kyc_status',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='investor',
            name='kyc_status',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
    ]
