# Generated by Django 5.2.7 on 2025-10-04 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OFAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=120, unique=True)),
                ('compe_code', models.CharField(max_length=3)),
                ('branch_code', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OFBillStatus',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OFCcAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=120, unique=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OFCreditDebitType',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OFCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_number', models.CharField(db_index=True, max_length=11)),
                ('civil_name', models.CharField(max_length=255)),
                ('social_name', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OFInstallmentStatus',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OFProductService',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OFAccountBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OFCcBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('minimum_payment', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofccaccount')),
                ('status', models.ForeignKey(db_column='status_code', on_delete=django.db.models.deletion.PROTECT, to='open_finance_mock.ofbillstatus')),
            ],
            options={
                'unique_together': {('account', 'bill_id')},
            },
        ),
        migrations.CreateModel(
            name='OFCcTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofccaccount')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_finance_mock.ofccbill')),
            ],
        ),
        migrations.AddField(
            model_name='ofccaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_finance_mock.ofcustomer'),
        ),
        migrations.AddField(
            model_name='ofaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_finance_mock.ofcustomer'),
        ),
        migrations.CreateModel(
            name='OFLoanContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_id', models.CharField(max_length=120, unique=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contract_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_finance_mock.ofcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='OFLoanInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instalment_id', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofloancontract')),
                ('status', models.ForeignKey(db_column='status_code', on_delete=django.db.models.deletion.PROTECT, to='open_finance_mock.ofinstallmentstatus')),
            ],
            options={
                'unique_together': {('contract', 'instalment_id')},
            },
        ),
        migrations.CreateModel(
            name='OFLoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofloancontract')),
                ('instalment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_finance_mock.ofloaninstallment')),
            ],
        ),
        migrations.CreateModel(
            name='OFAccountTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=120)),
                ('booking_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofaccount')),
                ('credit_debit_type', models.ForeignKey(db_column='credit_debit_type', on_delete=django.db.models.deletion.PROTECT, to='open_finance_mock.ofcreditdebittype')),
            ],
            options={
                'unique_together': {('account', 'transaction_id')},
            },
        ),
        migrations.CreateModel(
            name='OFCustomerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_finance_mock.ofcustomer')),
                ('product', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.PROTECT, to='open_finance_mock.ofproductservice')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
