# Generated by Django 5.2.7 on 2025-10-04 14:30

import consign_app.dataprev_mock.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockCLTCbo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MockCLTTipoInscricao',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MockINSSEspecie',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MockINSSSituacao',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MockINSSBeneficio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('numero_beneficio', models.CharField(max_length=30, unique=True)),
                ('data_inicio', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(db_column='codigo_especie', on_delete=django.db.models.deletion.PROTECT, to='dataprev_mock.mockinssespecie')),
                ('situacao', models.ForeignKey(db_column='codigo_situacao', on_delete=django.db.models.deletion.PROTECT, to='dataprev_mock.mockinsssituacao')),
            ],
        ),
        migrations.CreateModel(
            name='MockCLTRelacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('numero_inscricao', models.CharField(db_index=True, max_length=14)),
                ('data_admissao', models.DateField()),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('competencia', models.CharField(max_length=7)),
                ('pendencias', models.JSONField(blank=True, default=list, validators=[consign_app.dataprev_mock.models.validate_pendencias])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cbo', models.ForeignKey(db_column='cbo_codigo', on_delete=django.db.models.deletion.PROTECT, to='dataprev_mock.mockcltcbo')),
                ('tipo_inscricao', models.ForeignKey(db_column='tipo_inscricao', on_delete=django.db.models.deletion.PROTECT, to='dataprev_mock.mockclttipoinscricao')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['pendencias'], name='dataprev_mo_pendenc_eecb67_gin')],
            },
        ),
    ]
